[project]
name = "medeia-imdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawlee[beautifulsoup,curl-impersonate,playwright]>=1.3.1",
    "pandas>=3.0.0",
]
