name: Update IMDb Database

on:
  workflow_run:
    workflows:
      - Update Medeia Databases
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ORIGIN_EVENT: ${{ github.event.workflow_run.event || github.event_name }}
      IMDB_USER_ID: ur162389474

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install-deps chromium
          python -m playwright install chromium

      - name: Run update script
        run: |
          python src/medeia.py --no-medeia

      - name: Commit changes to /data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          COMMIT_MESSAGE="Update IMDb database"
          [[ "${ORIGIN_EVENT:-}" == "schedule" ]] && COMMIT_MESSAGE+=" ($(date +'%Y-%m-%d %H:00'))"

          git commit -m "$COMMIT_MESSAGE"
          git push

      - name: Upload storage directory artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storage
          path: storage/
